#ifndef CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_H
#define CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_H

typedef enum crankvm_system_primitive_number_e
{
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_ADD = 1,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_SUBTRACT = 2,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_LESS_THAN = 3,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_GREATER_THAN = 4,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_LESS_OR_EQUAL = 5,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_GREATER_OR_EQUAL = 6,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_EQUAL = 7,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_NOT_EQUAL = 8,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_MULTIPLY = 9,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_DIVIDE = 10,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_MOD = 11,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_DIV = 12,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_QUO = 13,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_BIT_AND = 14,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_BIT_OR = 15,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_BIT_XOR = 16,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_INTEGER_BIT_SHIFT = 17,

    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_PRIMITIVE_FAIL = 19,

    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_OBJECT_AT_PUT = 61,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_OBJECT_NEW = 70,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_OBJECT_NEW_WITH_ARG = 71,

    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_OBJECT_IDENTITY_EQUALS = 110,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_OBJECT_IDENTITY_NOT_EQUALS = 169,

    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_BLOCK_VALUE_ARGS0 = 201,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_BLOCK_VALUE_ARGS1 = 202,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_BLOCK_VALUE_ARGS2 = 203,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_BLOCK_VALUE_ARGS3 = 204,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_BLOCK_VALUE_ARGS4 = 205,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_BLOCK_VALUE_WITH_ARGUMENTS = 206,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_FULL_BLOCK_VALUE = 207,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_FULL_BLOCK_VALUE_WITH_ARGUMENTS = 208,

    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_BLOCK_VALUE_ARGS_FIRST = CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_BLOCK_VALUE_ARGS0,
    CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_BLOCK_VALUE_ARGS_LAST = CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_BLOCK_VALUE_ARGS4,

} crankvm_system_primitive_number_t;

#endif //CRANK_VM_SYSTEM_PRIMITIVE_NUMBER_H
